 #  
 # REMEDIATE THE FLAG
 # Copyright 2018 - Andrea Scaduto 
 # remediatetheflag@gmail.com
 # 
 # Licensed under the Apache License, Version 2.0 (the "License");
 # you may not use this file except in compliance with the License.
 # You may obtain a copy of the License at
 # 
 #     http://www.apache.org/licenses/LICENSE-2.0
 # 
 # Unless required by applicable law or agreed to in writing, software
 # distributed under the License is distributed on an "AS IS" BASIS,
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 # See the License for the specific language governing permissions and
 # limitations under the License.
 # 
Description: >
    RTF Satellite Gateway Template
Resources:
    VPC:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: https://s3-eu-west-1.amazonaws.com/rtf-templates/rtf-vpc.yaml
            Parameters:
                EnvironmentName:    RTF-VPC
                VpcCIDR:            10.0.0.0/16
                PublicSubnet1CIDR:  10.0.0.0/18
                PublicSubnet2CIDR:  10.0.64.0/18
                PrivateSubnet1CIDR: 10.0.128.0/18
                PrivateSubnet2CIDR: 10.0.192.0/18
    SecurityGroups:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: https://s3-eu-west-1.amazonaws.com/rtf-templates/rtf-security-groups.yaml
            Parameters: 
                EnvironmentName: RTF-SecurityGroups
                VPC: !GetAtt VPC.Outputs.VPC
    ALB:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: hhttps://s3-eu-west-1.amazonaws.com/rtf-templates/rtf-load-balancers.yaml
            Parameters:
                EnvironmentName: RTF-ALB
                VPC: !GetAtt VPC.Outputs.VPC
                Subnets: !GetAtt VPC.Outputs.PublicSubnets
                SecurityGroup: !GetAtt SecurityGroups.Outputs.LoadBalancerSecurityGroup
                LoadBalancerCertificateArn: arn:aws:acm:eu-central-1:427354328093:certificate/6ca2ff37-c8a0-4921-9fb9-d9e86653fab5
    ServicesECS:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: https://s3-eu-west-1.amazonaws.com/rtf-templates/rtf-ecs-services.yaml
            Parameters:
                EnvironmentName: RTF-Services
                InstanceType: t2.medium
                MinClusterSize: 1
                MaxClusterSize: 4
                VPC: !GetAtt VPC.Outputs.VPC
                SecurityGroup: !GetAtt SecurityGroups.Outputs.ServicesSecurityGroup
                Subnets: !GetAtt VPC.Outputs.PublicSubnets
                VolumeName: efs
                MountPoint: efs
    ExercisesECS:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: https://s3-eu-west-1.amazonaws.com/rtf-templates/rtf-ecs-exercises.yaml
            Parameters:
                EnvironmentName: rtf-exercises-pool
                InstanceType: m4.large
                MinClusterSize: 1
                MaxClusterSize: 4
                VPC: !GetAtt VPC.Outputs.VPC
                SecurityGroup: !GetAtt SecurityGroups.Outputs.ExercisesSecurityGroup
                Subnets: !GetAtt VPC.Outputs.PrivateSubnets
    MysqlService:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: https://s3-eu-west-1.amazonaws.com/rtf-templates/rtf-service-mysql.yaml
            Parameters:
                VPC: !GetAtt VPC.Outputs.VPC
                Cluster: !GetAtt ServicesECS.Outputs.Cluster
                DesiredCount: 1
                GuacRTFAdminUserPassword: 692sgbZtzZDJ
                MysqlGlobalUserPassword: null
                MysqlGuacUserPassword: rprbN8gSX74X
                MysqlRootUserPassword: CZaxHD5hz62r
                MysqlImage: 427354328093.dkr.ecr.eu-west-1.amazonaws.com/rtf-services:mysql-1.5
    GatewayService:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: https://s3-eu-west-1.amazonaws.com/rtf-templates/rtf-service-gateway.yaml
            Parameters:
                RTFMySQL: !GetAtt MysqlService.Outputs.MySQLService
                VPC: !GetAtt VPC.Outputs.VPC
                Cluster: !GetAtt ServicesECS.Outputs.Cluster
                DesiredCount: 1
                MaxCount: 4
                GatewayHostname: emea.remediatetheflag.net
                ListenerHTTP: !GetAtt ALB.Outputs.ListenerHTTP
                ListenerHTTPS: !GetAtt ALB.Outputs.ListenerHTTPS 
                MysqlGuacUserPassword: rprbN8gSX74X
                KiteImage: 427354328093.dkr.ecr.eu-west-1.amazonaws.com/rtf-services:kite-1.1
                GatewayImage: 427354328093.dkr.ecr.eu-west-1.amazonaws.com/rtf-services:gateway-1.4
                ECSServiceAutoScalingRoleARN: !GetAtt ServicesECS.Outputs.ECSServiceAutoScalingRole
Outputs:
    LoadBalancerUrl: 
        Description: The URL endpoint for the RTF platform
        Value: !GetAtt ALB.Outputs.LoadBalancerUrl